defaults:
  - base_model
  - override representation: field_painn


output_modules:
  - _target_: schnetpack.atomistic.Atomwise
    output_key: ${energy_key}
    n_in: ${model.representation.n_atom_basis}
    aggregation_mode: sum
  - _target_: schnetpack.atomistic.Response
    energy_key: ${energy_key}
    response_properties: ${response_properties}

outputs:
  - _target_: schnetpack.atomistic.ModelOutput
    name: ${energy_key}
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      mse:
        _target_: torchmetrics.regression.MeanSquaredError
    loss_weight: 0.05
  - _target_: schnetpack.atomistic.ModelOutput
    name: forces
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      mse:
        _target_: torchmetrics.regression.MeanSquaredError
    loss_weight: 0.95
  - _target_: schnetpack.atomistic.ModelOutput
    name: dipole_moment
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      mse:
        _target_: torchmetrics.regression.MeanSquaredError
    loss_weight: 0.00001
  - _target_: schnetpack.atomistic.ModelOutput
    name: polarizability
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      mse:
        _target_: torchmetrics.regression.MeanSquaredError
    loss_weight: 0.00001
